### ISSUE TITLE
I can not train yolov5 in jupyter

### ISSUE THREAD

**Issue by mohammadRezapor** [ultralytics/yolov5#10384]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

When I try to train the yolov5 model in jupyter I get the following error.
### YOLOv5 Component

Training, PyTorch Hub

### Bug

![image](https://user-images.githubusercontent.com/118986108/205356351-abb4c013-f837-442b-82b0-ef921f84084d.png)

### Environment

-YOLO : Yolov5 torch 1.13 cu116
-OS: windows 10
-Python: 3.9.7

### Minimal Reproducible Example

#!python train.py --img  415 --batch 16 --epochs 30 --data Face-Detection-14/data.yaml  --weights yolov5s.pt --cache

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mohammadRezapor seems to be caused by comet. Can you try `pip uninstall comet` and retrain?

@DN6

**Comment by mohammadRezapor** [comment]
I am uninstall the comet but still I have the same Erorr.
![image](https://user-images.githubusercontent.com/118986108/205399096-2d3a8d52-2619-40db-b013-db5586dc44aa.png)
![image](https://user-images.githubusercontent.com/118986108/205399215-a1a9bd30-4c15-436f-8ed4-10f294e5d3c2.png)

**Comment by glenn-jocher** [comment]
@mohammadRezapor read your own error message, it's saying your data yaml is incorrect.

<img width="1273" alt="Screenshot 2022-12-02 at 14 27 26" src="https://user-images.githubusercontent.com/26833433/205400585-6fcc65f5-63e7-4014-9dc3-74197319a582.png">


To train correctly your data must be in YOLOv5 format. Please see our [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) tutorial for full documentation on dataset setup and all steps required to start training your first model. A few excerpts from the tutorial:

### 1.1 Create dataset.yaml

[COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) is an example small tutorial dataset composed of the first 128 images in [COCO](http://cocodataset.org/#home) train2017. These same 128 images are used for both training and validation to verify our training pipeline is capable of overfitting. [data/coco128.yaml](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), shown below, is the dataset config file that defines 1) the dataset root directory `path` and relative paths to `train` / `val` / `test` image directories (or *.txt files with image paths) and 2) a class `names` dictionary:
```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
names:
  0: person
  1: bicycle
  2: car
  ...
  77: teddy bear
  78: hair drier
  79: toothbrush

```


### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<p align="center"><img width="750" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg"></p>

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>


### 1.3 Organize Directories

Organize your train and val images and labels according to the example below. YOLOv5 assumes  `/coco128` is inside a `/datasets` directory **next to** the `/yolov5` directory. **YOLOv5 locates labels automatically for each image** by replacing the last instance of `/images/` in each image path with `/labels/`. For example:
```bash
../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label
```

<p align="center"><img width="700" src="https://user-images.githubusercontent.com/26833433/134436012-65111ad1-9541-4853-81a6-f19a3468b75f.png"></p>
</details>

Good luck 🍀 and let us know if you have any other questions!
