### ISSUE TITLE
Extremely low accuracy

### ISSUE THREAD

**Issue by DhruvAwasthi** [ultralytics/yolov5#10532]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to train a detection model to detect the regions in packaged food product images that contain the nutrients and ingredients. So basically there are two classes -`ingredients` and `nutrients`.  
  
The sample original image may looks like this:  

![2482-brazil-nuts-8oz-v4 5 1_web_back](https://user-images.githubusercontent.com/66522260/208471656-d4a68603-7c12-4310-90e8-4fd67b4697ad.jpg)  
  
  
For this, I labeled the training data and exported the `*.txt` files in `yolo` format. The sample .txt file looks like this:
```
0 0.366042 0.395625 0.632083 0.127917
1 0.367083 0.491042 0.634167 0.062917
```

I labeled around `250` images for this, and then after using augmentations the dataset size grew to over `6,000` images. In the training dataset, I have also included around 10% of random background images.

I organized the training data into the following format:
```
dataset/
    train/
        images/
        labels/
    val/
        images/
        labels/
    test/
        images/
        labels/
```

For training, I tried with `YOLOv5s`, `YOLOv5m`, and `YOLOv5m6`. I am training the model for around 300 epochs, using a patience level of `10`and using the `Adam` optimizer.   But due to early stopping the model training is stopping in between around `10 and 20 epochs`.

The `opt.yaml` file looks like this:
```
weights: yolov5m6.pt
cfg: ''
hyp:
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
epochs: 300
batch_size: 4
imgsz: 896
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: Adam
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 10
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp
```
  

But even after all this, the confidence score that I am getting on the predictions on test images is too low, with the maximum being `0.016` and the lowest in the order of `0.0001xx`. These confidence scores are the same for the images that actually contain the classes that I want to predict, and for the images that do not contain these classes at all.    
  
  
Can you please tell me what you suspect is wrong here?

Thank you,
Dhruv
