### ISSUE TITLE
Degrees rotation augmentation messes up the size of the labels

### ISSUE THREAD

**Issue by Harmonised7** [ultralytics/yolov5#10639]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Examples with no degrees (found in /yolov5/runs/train/TheName#):
![train_batch0](https://user-images.githubusercontent.com/44095798/210079772-122e3f1f-1e6b-460d-9db1-fec180c7da78.jpg)
![train_batch1](https://user-images.githubusercontent.com/44095798/210079775-e297c03e-0a3d-4d3d-b4f0-01c2a4f7c3fe.jpg)
![train_batch2](https://user-images.githubusercontent.com/44095798/210079776-96bd9edb-78db-4f74-acd4-2f294b2a7441.jpg)

with 360 degrees:
![train_batch0](https://user-images.githubusercontent.com/44095798/210079875-f459164c-82e8-45d6-abce-5319f29fbe03.jpg)
![train_batch1](https://user-images.githubusercontent.com/44095798/210079877-9147c935-0566-4123-8472-10833cbc76f4.jpg)
![train_batch2](https://user-images.githubusercontent.com/44095798/210079879-5f6060dd-3355-4320-92ca-b6344813ba4e.jpg)

When rotation is introduced, the labels are strangely misplaced and expanded. (Also tried with 45 degrees, very similar issues)

Tried it with `hyp.scratch-high.yaml` and `hyp.scratch-med.yaml`, with the following changes:
flipud: 0.5
degrees: 360.0
fl_gamma: 0.5
copy_paste: 0.3
scale: 0.25

### Environment

$ git describe --tags
v7.0-53-g65071da

$ git rev-parse HEAD
65071da7181e2ede9d3514f20c88e6bd646af07c

(Pulled today)

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

$ python3 --version
Python 3.8.10

### Minimal Reproducible Example

```yaml
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# Hyperparameters for high-augmentation COCO training from scratch
# python train.py --batch 32 --cfg yolov5m6.yaml --weights '' --data coco.yaml --img 1280 --epochs 300
# See tutorials for hyperparameter evolution https://github.com/ultralytics/yolov5#tutorials

lr0: 0.01  # initial learning rate (SGD=1E-2, Adam=1E-3)
lrf: 0.1  # final OneCycleLR learning rate (lr0 * lrf)
momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4
warmup_epochs: 3.0  # warmup epochs (fractions ok)
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr
box: 0.05  # box loss gain
cls: 0.3  # cls loss gain
cls_pw: 1.0  # cls BCELoss positive_weight
obj: 0.7  # obj loss gain (scale with pixels)
obj_pw: 1.0  # obj BCELoss positive_weight
iou_t: 0.20  # IoU training threshold
anchor_t: 4.0  # anchor-multiple threshold
# anchors: 3  # anchors per output layer (0 to ignore)
fl_gamma: 0.5  # focal loss gamma (efficientDet default gamma=1.5)
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 360.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.25  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.5  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1.0  # image mosaic (probability)
mixup: 0.1  # image mixup (probability)
copy_paste: 0.3  # segment copy-paste (probability)
```

**--rect was used**
Started training with this .hyp file, checked found in /yolov5/runs/train/TheName#/train_batch#.jpg

### Additional

Tried tweaking several other parameters before figuring out `degrees` was causing the issue, such as:
scale
flipud
obj

These however had seemingly no effect on the issue, and it is only when `degrees` is changed that the issue was occurring.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
