### ISSUE TITLE
How to merge CNN in yaml?

### ISSUE THREAD

**Issue by administer03** [ultralytics/yolov5#11193]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

First, I have images dimension (1024, 1024, 7) but I need to use CNN to learn and reduce the channel instead. So, I would like to add my CNN model before YOLO network, now I do like this
```
backbone:
# my CNN model (1024, 1024, 7) --> (1024, 1024, 1)
  - conv:
      filters: 7
      size: 103
      stride: 1
      pad: same
      activation: relu
      input_shape: [null, 1024, 1024, 7]

  - conv:
      filters: 6
      size: 103
      stride: 1
      pad: same
      activation: relu
  - conv:
      filters: 5
      size: 103
      stride: 1
      pad: same
      activation: relu
  - conv:
      filters: 4
      size: 103
      stride: 1
      pad: same
      activation: relu
  - conv:
      filters: 3
      size: 103
      stride: 1
      pad: same
      activation: relu
  - conv:
      filters: 2
      size: 103
      stride: 1
      pad: same
      activation: relu
  - conv:
      filters: 1
      size: 103
      stride: 1
      pad: same
      activation: relu

  - conv:
      filters: 1
      size: 1
      stride: 1
      activation: relu

# concatinate with old backbone

  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]
```
