### ISSUE TITLE
How to specify yolov5 to train multiple folders?

### ISSUE THREAD

**Issue by kahvia1244** [ultralytics/yolov5#13240]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have some training data stored in multiple folders, but I don't want them to be mixed together. How can I specify multiple training folders?

**Comment by glenn-jocher** [comment]
@qjl1244281167 hello!

Thank you for your question. To train YOLOv5 with data stored in multiple folders without mixing them, you can specify the paths to these folders in your dataset configuration file. Here’s a step-by-step guide:

1. **Create a Dataset Configuration File**: This YAML file will define the paths to your training and validation datasets. Here’s an example structure:

    ```yaml
    train: 
      - /path/to/first/folder
      - /path/to/second/folder
      - /path/to/third/folder
    val: /path/to/validation/folder

    nc: 80  # number of classes
    names: ['class1', 'class2', ...]  # list of class names
    ```

2. **Modify the Training Command**: When you start training, specify this dataset configuration file using the `--data` argument. For example:

    ```bash
    python train.py --data /path/to/your_dataset.yaml --cfg yolov5s.yaml --weights yolov5s.pt --epochs 50
    ```

This setup allows you to keep your datasets in separate folders while training YOLOv5. If you encounter any issues or have further questions, please ensure you are using the latest version of YOLOv5 and its dependencies.

Feel free to reach out if you need more assistance. Happy training! 😊
