### ISSUE TITLE
Can I load partial pretrain weights

### ISSUE THREAD

**Issue by snow-tyan** [ultralytics/yolov5#3293]
## ❔Question
I want to load only the weights of backbone, while the weights of neck and head use initial weights
what should i do

## Additional 
I have added some layers to yolov5 module, but I don't have much time to train COCO datasets. I want to make some comparison with yolov5l on my datasets, so I just want to load backbone weights

**Comment by yannclaes** [comment]
When you mention initial weights, do you talk about COCO-pretrained-weights or randomly initialized weights? Could you provide your model.yaml file, if that's where you added some layers?

**Comment by glenn-jocher** [comment]
@snow-tyan  👋 Hello! Thanks for asking about pretrained weights. See our guide below.
 
## Model Selection

Larger models like YOLOv5x and [YOLOv5x6](https://github.com/ultralytics/yolov5/releases/tag/v5.0) will produce better results in nearly all cases, but have more parameters, require more CUDA memory to train, and are slower to run. For **mobile** deployments we recommend YOLOv5s/m, for **cloud** deployments we recommend YOLOv5l/x. See our README [table](https://github.com/ultralytics/yolov5#pretrained-checkpoints) for a full comparison of all models. 

<p align="center"><img width="700" alt="YOLOv5 Models" src="https://user-images.githubusercontent.com/26833433/103595982-ab986000-4eb1-11eb-8c57-4726261b0a88.png"></p>

- **Start from Pretrained weights.** Recommended for small to medium sized datasets (i.e. VOC, VisDrone, GlobalWheat). Pass the name of the model to the `--weights` argument. Models download automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases).
```bash
python train.py --data custom.yaml --weights yolov5s.pt
                                             yolov5m.pt
                                             yolov5l.pt
                                             yolov5x.pt
```
- **Start from Scratch.** Recommended for large datasets (i.e. COCO, Objects365, OIv6). Pass the model architecture yaml you are interested in, along with an empty `--weights ''` argument:
```bash
python train.py --data custom.yaml --weights '' --cfg yolov5s.yaml
                                                      yolov5m.yaml
                                                      yolov5l.yaml
                                                      yolov5x.yaml
```

**Comment by snow-tyan** [comment]
@glenn-jocher Thanks for reply. I think my question may be a little strange, I just want to load backbone-weights 😂
By the way, I found lots of .yaml file on folder (models/hub/). Do they have weights file, can you provide the download link(such as drive.google.com)

**Comment by yannclaes** [comment]
@snow-tyan Weight files can be found [here](https://github.com/ultralytics/yolov5/releases). What comes to my mind is that you could load the entire model in a temporary model, as is done here:
https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L84-L92

Then you could initialize a model with random weights, as is done here:
https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L94-L95

And replace the backbone of this new model with the backbone of the temporary model, by replacing the appropriate ```model.model``` layers. I think this should be feasible ;-)

**Comment by glenn-jocher** [comment]
I created an `intersect_dicts()` function to populate a randomly initialized model with pretrained weights here. All matching keys not in the exclude list with matching value shapes are used. You can extend the exclude list to exclude any layers you don't want transferred.
https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L89-L91

**Comment by snow-tyan** [comment]
@glenn-jocher @yannclaes thanks, I'v noticed that function, It's awesome design

**Comment by dk-teknologisk-mlnn** [comment]
When I changed the model and tried using pretrained weights I noticed it used the weights from the model up until my change. e.g. (for good round numbers ) it said something like " using weights from yolov5s.pt 130 / 280 layers".

**Comment by chinhong11** [comment]
@glenn-jocher Hi, may I know if it is possible for me to take the original yolov8s.pt weights and train them on a modified yolov8s.yaml file, for example, with an added attention module like CBAM on the structure? Can the weights be transferred instead of starting training from scratch? I tried this command but it seems still start training from scratch:(

My code is something like this:
···
model = YOLO("ultralytics/models/v8/yolov8s-cbam.yaml").load('yolov8s.pt')
model.train(**{'cfg':'ultralytics/yolo/cfg/train.yaml'})
···

My yaml file is as below:
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, CBAM, [7]] # 1
  - [-1, 1, Conv, [128, 3, 2]]  # 2-P2/4
  - [-1, 1, CBAM, [7]] # 3
  - [-1, 3, C2f, [128, True]]   # 4
  - [-1, 1, Conv, [256, 3, 2]]  # 5-P3/8
  - [-1, 1, CBAM, [7]] # 6
  - [-1, 6, C2f, [256, True]]   # 7
  - [-1, 1, Conv, [512, 3, 2]]  # 8-P4/16
  - [-1, 1, CBAM, [7]] # 9
  - [-1, 6, C2f, [512, True]]   # 10
  - [-1, 1, Conv, [1024, 3, 2]]  # 11-P5/32
  - [-1, 1, CBAM, [7]] # 12
  - [-1, 3, C2f, [1024, True]]  # 13
  - [-1, 1, SPPF, [1024, 5]]  # 14

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] # 15
  - [[-1, 9], 1, Concat, [1]]  # cat backbone P4 # 16
  - [-1, 3, C2f, [512]]  # 17

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] # 18
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P3 # 19
  - [-1, 3, C2f, [256]]  # 20 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]] # 21
  - [[-1, 17], 1, Concat, [1]]  # cat head P4 # 22
  - [-1, 3, C2f, [512]]  # 23 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]] # 24
  - [[-1, 14], 1, Concat, [1]]  # cat head P5 # 25
  - [-1, 3, C2f, [1024]]  # 26 (P5/32-large)

  - [[20, 23, 26], 1, Detect, [nc]]  # Detect(P3, P4, P5) # 27
```
