### ISSUE TITLE
Dockerhub disabling Autobuild for Free tier

### ISSUE THREAD

**Issue by NanoCode012** [ultralytics/yolov5#3526]
## ❔Question

Hello, I would like to ask whether Yolov5 on Docker hub is using the Free tier or a paid tier? I just saw a blog that they are removing it from the Free tier. This could mean that Docker hub versions of Yolov5 could break soon.

https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

## Additional context

I think Yolov5 could be eligible for their OpenSource program to continue getting Autobuild for free.

https://www.docker.com/blog/expanded-support-for-open-source-software-projects/

**Comment by glenn-jocher** [comment]
@NanoCode012 uh oh! Yes we are on the free tier using Docker hub autobuild on each push to master. Thanks for the blogpost!

I suppose we'll have to move to one of their paid plans :*(

**Comment by NanoCode012** [comment]
This is quite unfortunate. I wonder if using Github Actions to build the image would be more efficient or perhaps there are other services that can do it.

**Comment by glenn-jocher** [comment]
@NanoCode012 actually that's not a bad idea. We could add an action on each master update. The Docker build code is really simple, but I just realized there would be an authentication issue when docker received the push...

https://github.com/ultralytics/yolov5/blob/f3c3d2ce5d85ba77336a9d0a87c6a446732cdda6/Dockerfile#L26-L27

**Comment by NanoCode012** [comment]
You can use Secrets in Github Actions. You can pass in the credentials. I'm not sure if they allow App Passwords or you may need to use the real dockerhub credentials.

I found the below in Github's doc https://docs.github.com/en/actions/guides/publishing-docker-images

```yaml
name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: my-docker-hub-namespace/my-docker-hub-repository:latest
```

I think the one concern I had was how many "minutes" of Github Actions do we get per month or is it unlimited?

Edit: It would seem public repo gets unlimited free Actions. This should be the best way then?
