### ISSUE TITLE
KITTI and YOLO -> no predictions

### ISSUE THREAD

**Issue by mk-inside** [ultralytics/yolov5#4036]
Hi to all,

I have a problem using YOLOv5 and the kitti dataset. Using the small models (YOLOv5s to YOLOv5x) is working, but my mAP is ~ 30% max. For my master thesis we should reach a minimum mAP about 50%. That's the reason why we also want to use the large models of YOLOv5, like YOLOv5l6. The problem: Using the "6" models, YOLO does not make any predictions. The tensors after self.model(x) are always empty - in training and validation step.

Do you have any ideas what's the reason for that or how we can improve the performance with the "small" nets?

For any idea I would be very grateful!

All the best, mk-inside

My hyperparams:
```
hyp:
  lr0: 0.0053  # initial learning rate (SGD=1E-2, Adam=1E-3)
  lrf: 0.2  # final OneCycleLR learning rate (lr0 * lrf)
  momentum: 0.871  # SGD momentum/Adam beta1
  weight_decay: 0.00065  # optimizer weight decay 5e-4
  giou: 0.0287
  warmup_epochs: 3.0  # warmup epochs (fractions ok)
  warmup_momentum: 0.8  # warmup initial momentum
  warmup_bias_lr: 0.1  # warmup initial bias lr
  box: 0.05  # box loss gain
  cls: 0.381  # cls loss gain
  cls_pw: 0.531  # cls BCELoss positive_weight
  obj: 0.518  # obj loss gain (scale with pixels)
  obj_pw: 0.956  # obj BCELoss positive_weight
  iou_t: 0.2  # IoU training threshold
  anchor_t: 2.0  # anchor-multiple threshold
  # anchors: 3  # anchors per output layer (0 to ignore)
  fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
  hsv_h: 0.0205  # image HSV-Hue augmentation (fraction)
  hsv_s: 0.9  # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.604  # image HSV-Value augmentation (fraction)
  degrees: 0.508  # image rotation (+/- deg)
  translate: 0.153  # image translation (+/- fraction)
  scale: 0.9  # image scale (+/- gain)
  shear: 0.987  # image shear (+/- deg)
  perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
  flipud: 0.00987  # image flip up-down (probability)
  fliplr: 0.395  # image flip left-right (probability)
  mosaic: 1.0  # image mosaic (probability)
  mixup: 0.262  # image mixup (probability)

```
