### ISSUE TITLE
obj cls and box hyperparameters raise error in wandb sweep optimization

### ISSUE THREAD

**Issue by thanos-sakelliou** [ultralytics/yolov5#5146]
If `obj` (probably `cls` and `box` too) hyperparameter is declared in sweep.yaml file for tuning with wandb, the second time the agent calls for a sweep, an error rises:
`wandb: ERROR Error while calling W&B API: 1.0834083 is not a permitted value of the categorical hyperparameter obj in the current sweep. (<Response [400]>)`

This seems to be caused by the following lines:
https://github.com/ultralytics/yolov5/blob/956be8e642b5c10af4a1533e09084ca32ff4f21f/train.py#L245-L247

In this case i am using `obj=0.64107`, which is scaled by the above code to `1.0834083`  and passed in the wandb logs.

**Comment by thanos-sakelliou** [comment]
This problem also scales if the sweeps do happen. If the parameter is declared as a range in .yaml (and not categorical) that includes the scaled up number, then the optimization happens, but the logged/displayed values in the wandb portal are wrong.  This leads to various problems with wandb sweeps.

**Comment by glenn-jocher** [comment]
@thanos-sakelliou 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Can you help by providing directions to create a minimum reproducible example of your issues?

@AyushExel can you take a look at this? Thanks!

**Comment by AyushExel** [comment]
@thanos-sakelliou Hi, can you provide the .yaml file for sweep config that you're using so I can reproduce this? Thanks!

**Comment by thanos-sakelliou** [comment]
@AyushExel Hello, yes sure. Here are the contents of my `sweep.yaml` file.

 Some extra insights: 
- Default `sweep.yaml` with `method: random` seems to work fine, but some of the values logged in wandb are different (probably the scaled up ones I mentioned) from the default yaml file. 
- I tried to keep some params static (e.g. `obj`) so to focus on others. The first run always succeeds but the second one fails. 

```
method: bayes
metric:
  goal: maximize
  name: metrics/recall
parameters:
  img:
    values: [832]
  weights:
    values: [yolov5l.pt]
  batch_size:
    values: [6]
  data:
    values:
    - data/eden_handpicked_v3.yaml
  epochs:
    values: [200]
  lr0:
    distribution: uniform
    min: 1e-4
    max: 1e-1
  lrf:
    distribution: uniform
    min: 0.01
    max: 1.0
  momentum:
    distribution: uniform
    min: 0.6
    max: 0.98
  weight_decay:
    distribution: uniform
    min: 0.0
    max: 0.001
  warmup_epochs:
    distribution: uniform
    min: 0.0
    max: 5.0
  warmup_momentum:
    distribution: uniform
    min: 0.0
    max: 0.95
  warmup_bias_lr:
    distribution: uniform
    min: 0.0
    max: 0.3
  box:
    values: [0.04365]
  cls:
    values: [0]
  cls_pw:
    values: [0]
  obj:
    values: [0.64107]
  obj_pw:
    values: [0.76736]
  iou_t:
    values: [0.2]
  anchor_t:
    values: [4.45427]
  fl_gamma:
    values: [0.0]
  hsv_h:
    values: [0.0]
  hsv_s:
    values: [0.0]
  hsv_v:
    values: [0.0]
  degrees:
    values: [0.0]
  translate:
    values: [0.0]
  scale:
    values: [0.0]
  shear:
    values: [0.0]
  perspective:
    values: [0.0]
  flipud:
    values: [0.0]
  fliplr:
    values: [0.5]
  mosaic:
    values: [0.0]
  mixup:
    values: [0.0]
  copy_paste:
    values: [0.0]
  anchors:
    values: [2.8649]
program: utils/loggers/wandb/sweep.py

```
