### ISSUE TITLE
Training with single class

### ISSUE THREAD

**Issue by Karol-G** [ultralytics/yolov5#5568]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I am training on a dataset with a single class.
Then `nc` has to be `1`, correct?
And in the label txt files this class has to be denoted with `0`, correct?

Here my dataset YML:

```yml
path: /home/k539i/Documents/datasets/preprocessed/node21
train: ./train/images
val: ./val/images

# Classes
nc: 1  # number of classes
names: ['nodule']  # class names
```

Best
Karol
