### ISSUE TITLE
train model on multiple folders/sources

### ISSUE THREAD

**Issue by Borda** [ultralytics/yolov5#662]
## 🚀 Feature

According the wiki now we can train model just from one source/folder. I would be interested in having option to define multiple folders...

## Motivation

My vase is that I have several datasets for the same problem v1, v2, v3, etc and I am interested which datasets or their combination gives what results, e.g. train model on v1 only or v2+v3, but I do not want to create a copy all these combinations as it is quite waste of space...

## Pitch
the solution shall be quite simple, just allow multiple folders in training/dataset config and eventually update dataloader...

**Comment by glenn-jocher** [comment]
@Borda this already exists. If you look at coco128.yaml for example you can see the options for defining train and val datasets. You can specify a *.txt file of image paths, a directory, or a list of the first two options:
https://github.com/ultralytics/yolov5/blob/93684531c6e71547667ee19df6ddb94af3c8c80d/data/coco128.yaml#L10-L13

**Comment by glenn-jocher** [comment]
@Borda if you mix datasets though, you should make sure that they have the same classes. To see an example of this, you can simply change L11 to this to use two train sets:

```yaml
 train: 
  - ../coco128/images/train2017/  # 128 images 
  - ../coco128/images/train2017/  # 128 images 
 val: ../coco128/images/train2017/  # 128 images 
```
