### ISSUE TITLE
How Can I use multi-label train and inference？

### ISSUE THREAD

**Issue by WangRongsheng** [ultralytics/yolov5#7648]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Usually the inference picture is like this（only one class：`car`）：
![](https://s1.ax1x.com/2022/04/30/LzIDyV.png)
But I hope it is like（multi label：`car` and `white`）：
![](https://s1.ax1x.com/2022/04/30/LzILYd.png)
my `data.yaml`：
```yaml
train: ./dataset/train/images
val: ./dataset/valid/images

nc: 2
names: ['car','cup']
```
How can I modify it？
