### ISSUE TITLE
Data Loader Error - ValueError

### ISSUE THREAD

**Issue by ryanfont80** [ultralytics/yolov5#7943]
I am having an issue with a data set - it is all images. I can confirm they all work, are not blank or missing, and all have the proper label files associated. Yet EVERY time I try to load the data set I get this:

Transferred 955/963 items from yolov5x6.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 159 weight (no decay), 163 weight, 163 bias
train: Scanning '/home/citadel/yolov5/data/datasets/24gmodel/train/labels.cache' images and labels... 43
train: Caching images (9.7GB ram):  18%|█▊        | 7866/43498 [00:04<00:19, 1826.71it/s]               
Traceback (most recent call last):
  File "/home/citadel/yolov5/train.py", line 670, in <module>
    main(opt)
  File "/home/citadel/yolov5/train.py", line 565, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/citadel/yolov5/train.py", line 221, in train
    train_loader, dataset = create_dataloader(train_path,
  File "/home/citadel/yolov5/utils/dataloaders.py", line 114, in create_dataloader
    dataset = LoadImagesAndLabels(
  File "/home/citadel/yolov5/utils/dataloaders.py", line 524, in __init__
    for i, x in pbar:
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/citadel/yolov5/utils/dataloaders.py", line 659, in load_image
    im = np.load(fn, allow_pickle=True)
  File "/home/citadel/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 430, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "/home/citadel/.local/lib/python3.10/site-packages/numpy/lib/format.py", line 786, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 0 into shape (640,640,3)
Traceback (most recent call last):
  File "/home/citadel/yolov5/train.py", line 670, in <module>
    main(opt)
  File "/home/citadel/yolov5/train.py", line 565, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/citadel/yolov5/train.py", line 221, in train
    train_loader, dataset = create_dataloader(train_path,
  File "/home/citadel/yolov5/utils/dataloaders.py", line 114, in create_dataloader
    dataset = LoadImagesAndLabels(
  File "/home/citadel/yolov5/utils/dataloaders.py", line 524, in __init__
    for i, x in pbar:
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/citadel/yolov5/utils/dataloaders.py", line 659, in load_image
    im = np.load(fn, allow_pickle=True)
  File "/home/citadel/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 430, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "/home/citadel/.local/lib/python3.10/site-packages/numpy/lib/format.py", line 786, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 0 into shape (640,640,3)

Any ideas?

**Comment by ryanfont80** [comment]
The error is happening in the exact same spot every time.. even deleted the image that was at item #7866 in case there was some weird corruption.

**Comment by glenn-jocher** [comment]
@ryanfont80 not sure why one would express surprise at deterministic behavior. Follow dataset guidelines below.

👋 Hello! Thanks for asking about YOLOv5 🚀 **dataset formatting**. To train correctly your data must be in YOLOv5 format. Please see our [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) tutorial for full documentation on dataset setup and all steps required to start training your first model. A few excerpts from the tutorial:

### 1.1 Create dataset.yaml

[COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) is an example small tutorial dataset composed of the first 128 images in [COCO](http://cocodataset.org/#home) train2017. These same 128 images are used for both training and validation to verify our training pipeline is capable of overfitting. [data/coco128.yaml](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), shown below, is the dataset config file that defines 1) the dataset root directory `path` and relative paths to `train` / `val` / `test` image directories (or *.txt files with image paths), 2) the number of classes `nc` and 3) a list of class `names`:
```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes
nc: 80  # number of classes
names: [ 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
         'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
         'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
         'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
         'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
         'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
         'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
         'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
         'hair drier', 'toothbrush' ]  # class names
```


### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>


### 1.3 Organize Directories

Organize your train and val images and labels according to the example below. YOLOv5 assumes  `/coco128` is inside a `/datasets` directory **next to** the `/yolov5` directory. **YOLOv5 locates labels automatically for each image** by replacing the last instance of `/images/` in each image path with `/labels/`. For example:
```bash
../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label
```

<p align="center"><img width="700" src="https://user-images.githubusercontent.com/26833433/134436012-65111ad1-9541-4853-81a6-f19a3468b75f.png"></p>
</details>


Good luck 🍀 and let us know if you have any other questions!
