### ISSUE TITLE
COCO Finetuning Evolution

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/yolov5#918]
## 🚀 Feature
COCO finetuning evolution will attempt to evolve hyps better tuned to finetune COCO from official (pretrained COCO) YOLOv5 weights in https://github.com/ultralytics/yolov5/releases/tag/v3.0

A docker image has been created at ultralytics/yolov5:evolve with a new hyp.coco.finetune.yaml file identical to hyp.scratch.yaml, but with added hyps for warmup evolution:

```yaml
# Hyperparameters for COCO finetuning
# python train.py --batch 32 --weights yolov5m.pt --data coco.yaml --img 640 --epochs 30
# See tutorials for hyperparameter evolution https://github.com/ultralytics/yolov5#tutorials


lr0: 0.01  # initial learning rate (SGD=1E-2, Adam=1E-3)
lrf: 0.2  # final OneCycleLR learning rate (lr0 * lrf)
momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4
warmup_epochs: 1.5  # warmup epochs (fractions ok)
warmup_momentum: 0.5  # warmup initial momentum
warmup_bias_lr: 0.05  # warmup initial bias lr
giou: 0.05  # box loss gain
cls: 0.5  # cls loss gain
cls_pw: 1.0  # cls BCELoss positive_weight
obj: 1.0  # obj loss gain (scale with pixels)
obj_pw: 1.0  # obj BCELoss positive_weight
iou_t: 0.20  # IoU training threshold
anchor_t: 4.0  # anchor-multiple threshold
anchors: 3.0  # anchors per output grid (0 to ignore)
fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.5  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mixup: 0.0  # image mixup (probability)
```

Image train.py has been updated to accept these additional hyps:
<img width="1942" alt="Screen Shot 2020-09-05 at 1 19 41 PM" src="https://user-images.githubusercontent.com/26833433/92313002-4e2fe900-ef7b-11ea-8aed-d1c36dfcb630.png">

Initial evolution will use a shorter training schedule to maximize evolution rate for 300 generations:
```
python train.py --batch 32 --weights yolov5m.pt --data coco.yaml --epochs 10 --bucket ult/evolve/coco/fine10
```

Pending analysis of above results, a longer period may be used to reduce overfitting and improve results:
```
python train.py --batch 32 --weights yolov5m.pt --data coco.yaml --epochs 30 --bucket ult/evolve/coco/fine30
```

@NanoCode012 and anyone with available GPUs is invited to participate! We need all of the help we can get to improve our hyps to help people better train on their own custom datasets. Our docker image reads and writes evolution results from each generation from a centralized GCP bucket, so multiple distributed nodes can evolve simultaneously and seamlessly. The steps on a unix machine are:

### 1. Navigate to (or download) COCO

Open a new terminal and navigate to the directory containing `/coco`, or download using `yolov5/data/scripts/get_coco.sh`:
<img width="959" alt="Screen Shot 2020-09-05 at 1 43 55 PM" src="https://user-images.githubusercontent.com/26833433/92313212-124a5300-ef7e-11ea-87d9-a6b119e921ed.png">

### 2. Pull Image

Pull and run docker image in interactive mode with access to GPUs, mounting coco volume:
```bash
t=ultralytics/yolov5:evolve_coco_fine10 && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all -v "$(pwd)"/coco:/usr/src/coco $t
```
<img width="1372" alt="Screen Shot 2020-09-05 at 1 47 15 PM" src="https://user-images.githubusercontent.com/26833433/92313236-5ccbcf80-ef7e-11ea-9f99-c00138c1aad1.png">

### 3. Evolve

From within the running image, select your `--device` and run this loop to start evolution. When you want to free up resources or stop contributing, simply terminate the docker container. Run `sudo docker ps` to display running containers, and then `sudo docker kill CONTAINER_ID`. Restart anytime from step 2.
```bash
while true; do
  python train.py --batch 32 --weights yolov5m.pt --data coco.yaml --img 640 --epochs 10 --evolve --bucket ult/evolve/coco/fine10 --device 0
done
```

Optional parallel evolution on a multi-GPU machine, one container per GPU for devices 0, 1, 2, 3:
```bash
for i in 0 1 2 3; do
  t=ultralytics/yolov5:evolve_coco_fine10 && sudo docker pull $t && sudo docker run -d --ipc=host --gpus all -v "$(pwd)"/coco:/usr/src/coco $t bash utils/evolve.sh $i
  sleep 60 # avoid simultaneous evolve.txt read/write
done
```

### 4. Batchsize

--batch 32 uses about 11.9GB of CUDA mem. If you are using a 2080Ti with 11GB you can use the same commands above with --batch 28 or 24 with minimal impact on results.
