### ISSUE TITLE
TypeError: Class labels must be a dictionary of numbers to string

### ISSUE THREAD

**Issue by Sodek93** [ultralytics/yolov5#9194]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, i am trying to train custom data with CLI:

python yolov5/train.py --img 640 --batch 16 --epochs 3 --data dataset.yaml --weights yolov5s.pt

dataset.yaml:
```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../AutomaticGeneratedData  # dataset root dir
train: 2022-08-25_10:38:35/images  # train images (relative to 'path') 128 images
val: 2022-08-25_10:49:49/images  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
nc: 11
names:
  0: nothing
  1: plate
  2: cup
  3: rack
  4: glass
  5: bottle
  6: lid
  7: somemore
  8: tupper
  9: dude
  10: car
```

when i run 

python yolov5/train.py --img 640 --batch 16 --epochs 3 --data dataset.yaml --weights yolov5s.pt

i get the following error:

```
Traceback (most recent call last):
  File "yolov5/train.py", line 648, in <module>
    main(opt)
  File "yolov5/train.py", line 543, in main
    train(opt.hyp, opt, device, callbacks)
  File "yolov5/train.py", line 372, in train
    results, maps, _ = val.run(data_dict,
  File "/home/xxx/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/ProjectReforged/yolov5/val.py", line 256, in run
    callbacks.run('on_val_image_end', pred, predn, path, names, im[si])
  File "/home/xxx//ProjectReforged/yolov5/utils/callbacks.py", line 71, in run
    logger['callback'](*args, **kwargs)
  File "/home/xxx/ProjectReforged/yolov5/utils/loggers/__init__.py", line 124, in on_val_image_end
    self.wandb.val_one_image(pred, predn, path, names, im)
  File "/home/xxx/ProjectReforged/yolov5/utils/loggers/wandb/wandb_utils.py", line 506, in val_one_image
    self.bbox_media_panel_images.append(wandb.Image(im, boxes=boxes, caption=path.name))
  File "/home/xxx/venv//lib/python3.8/site-packages/wandb/sdk/data_types/image.py", line 147, in __init__
    self._set_initialization_meta(grouping, caption, classes, boxes, masks)
  File "/home/xxx/venv/lib/python3.8/site-packages/wandb/sdk/data_types/image.py", line 175, in _set_initialization_meta
    boxes_final[key] = BoundingBoxes2D(box_item, key)
  File "/home/xxx/venv/lib/python3.8/site-packages/wandb/sdk/data_types/helper_types/bounding_boxes_2d.py", line 214, in __init__
    super().__init__(val)
  File "/home/xxx/venv/lib/python3.8/site-packages/wandb/sdk/data_types/base_types/json_metadata.py", line 30, in __init__
    self.validate(val)
  File "/home/xxx/venv/lib/python3.8/site-packages/wandb/sdk/data_types/helper_types/bounding_boxes_2d.py", line 258, in validate
    raise TypeError(
TypeError: Class labels must be a dictionary of numbers to string
```
But i think i have the correct syntax in the above dataset.yaml, right?

**Comment by glenn-jocher** [comment]
@Sodek93 👋 Hello! Thanks for asking about YOLOv5 🚀 **dataset formatting**. To train correctly your data must be in YOLOv5 format. Please see our [Train Custom Data](https://github.com/ultralytics/yolov5/issues/36) tutorial for full documentation on dataset setup and all steps required to start training your first model. A few excerpts from the tutorial:

### 1.1 Create dataset.yaml

[COCO128](https://www.kaggle.com/ultralytics/coco128) is an example small tutorial dataset composed of the first 128 images in [COCO](http://cocodataset.org/#home) train2017. These same 128 images are used for both training and validation to verify our training pipeline is capable of overfitting. [data/coco128.yaml](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), shown below, is the dataset config file that defines 1) the dataset root directory `path` and relative paths to `train` / `val` / `test` image directories (or *.txt files with image paths), 2) the number of classes `nc` and 3) a list of class `names`:
```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes
nc: 80  # number of classes
names: [ 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
         'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
         'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
         'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
         'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
         'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
         'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
         'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
         'hair drier', 'toothbrush' ]  # class names
```


### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>


### 1.3 Organize Directories

Organize your train and val images and labels according to the example below. YOLOv5 assumes  `/coco128` is inside a `/datasets` directory **next to** the `/yolov5` directory. **YOLOv5 locates labels automatically for each image** by replacing the last instance of `/images/` in each image path with `/labels/`. For example:
```bash
../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label
```

<p align="center"><img width="700" src="https://user-images.githubusercontent.com/26833433/134436012-65111ad1-9541-4853-81a6-f19a3468b75f.png"></p>
</details>


Good luck 🍀 and let us know if you have any other questions!

**Comment by glenn-jocher** [comment]
@Sodek93 👋 Hello! Thanks for asking about YOLOv5 🚀 **dataset formatting**. To train correctly your data must be in YOLOv5 format. Please see our [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) tutorial for full documentation on dataset setup and all steps required to start training your first model. A few excerpts from the tutorial:

### 1.1 Create dataset.yaml

[COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) is an example small tutorial dataset composed of the first 128 images in [COCO](http://cocodataset.org/#home) train2017. These same 128 images are used for both training and validation to verify our training pipeline is capable of overfitting. [data/coco128.yaml](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), shown below, is the dataset config file that defines 1) the dataset root directory `path` and relative paths to `train` / `val` / `test` image directories (or *.txt files with image paths) and 2) a class `names` dictionary:
```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
names:
  0: person
  1: bicycle
  2: car
  ...
  77: teddy bear
  78: hair drier
  79: toothbrush

```


### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<p align="center"><img width="750" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg"></p>

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>


### 1.3 Organize Directories

Organize your train and val images and labels according to the example below. YOLOv5 assumes  `/coco128` is inside a `/datasets` directory **next to** the `/yolov5` directory. **YOLOv5 locates labels automatically for each image** by replacing the last instance of `/images/` in each image path with `/labels/`. For example:
```bash
../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label
```

<p align="center"><img width="700" src="https://user-images.githubusercontent.com/26833433/134436012-65111ad1-9541-4853-81a6-f19a3468b75f.png"></p>
</details>

Good luck 🍀 and let us know if you have any other questions!

**Comment by Sodek93** [comment]
Hi, thanks for your advice but i can't find my difference to the example.

Here are my Files:
An Label:
```
5 0.461979 0.44375 0.923958 0.05
5 0.45625 0.893359 0.79375 0.149219
0 0.315625 0.38125 0.15625 0.0859375

```
dataset.yaml:
```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../AutomaticGeneratedData  # dataset root dir
train: 2022-08-29_14:02:03/images  # train images (relative to 'path') 128 images
val: 2022-08-29_14:46:01/images  # val images (relative to 'path') 128 images
test:  2022-08-20_15:29:38/images

# Classes (80 COCO classes)
nc: 10
names:
  0: plate
  1: cup
  2: rack
  3: glass
  4: bottle
  5: lid
  6: sprayarm
  7: tupper
  8: pot
  9: plastic

```
my Directories are organized as in example and it does find my files and the Labels. I also find train_batch0.jpg in the Results Path ./runs/train/exp33.

As you can see i have this line 
nc: 10 
in my dataset.yaml. If i leave this out, just like you do it in the example i get an error.

**Comment by glenn-jocher** [comment]
@Sodek93 your YOLOv5 is out of date, just update it. To update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by dimka11** [comment]
I have the same issue with last yolov5 and yolov7, when I did use wandb.

**Comment by glenn-jocher** [comment]
@dimka11 YOLOv5 model yamls have been updated to use dictionary classes, i.e.:

```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
names:
  0: person
  1: bicycle
  2: car
  ...
  77: teddy bear
  78: hair drier
  79: toothbrush
```
