### ISSUE TITLE
How suspend image mixing

### ISSUE THREAD

**Issue by Borda** [ultralytics/yolov5#931]
## ❔Question

I want to run image training with quite a conservative augmentation so just flipping and small translation/zoom, but the samples are always quite wild... I have set the following parameters in hyp config:
```yaml
degrees: 0.0  # image rotation (+/- deg)
translate: 0.0  # image translation (+/- fraction)
scale: 0.0  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
mixup: 0.0  # image mixup (probability)
```
but still getting these batches...
![train_batch1](https://user-images.githubusercontent.com/6035284/92476754-bed73f80-f1df-11ea-8ed0-23fa7d48306c.jpg)
